function plotfunc(xHistory, fHistory, DfHistory, max_p)
    iter = length(fHistory);
    figure(10100)
    subplot(2,1,1)
    semilogy(1:iter, fHistory)
    xlabel('iteration')
    ylabel('F')
%     subplot(3,1,2)
%     plot(1:iter, xHistory(1:16,1:iter))
%     xlabel('iteration')
%     ylabel('change in geom. parameters')
    subplot(2,1,2)
    plot(1:iter, xHistory(1:max_p,1:iter))
    xlabel('iteration')
    ylabel('change in voltage parameters')
end